site:
  title: "Daily Signal"
  description: "Automated daily digest from public-domain/open sources."
  base_url: "https://<your-username>.github.io/<your-repo>"
  timezone: "America/Vancouver"
  cname: ""

monetization:
  tip_url: ""
  ad_snippet: ""

email:
  enabled: false
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  use_tls: true
  from_addr: "you@example.com"
  to_addr: "you@example.com"
  username: "you@example.com"
  app_password: "APP_PASSWORD"

sources:
  nasa_apod: true
  usgs_quakes: true
  noaa_space: true
  on_this_day: true
