site:
  title: "Daily Signal"
  description: "Automated daily digest from public-domain/open sources."
  base_url: "https://aidieselprof.github.io/daily-signal"
  timezone: "America/Vancouver"
  cname: ""
  google_site_verification: "jcC0oX1CyN4oBwXFX3EiYJJcWGaY-KOLp4O72nV9L3M"
  bing_site_verification: ""

monetization:
  tip_url: "https://ko-fi.com/dailysignal"
  ad_snippet: |-
    <script src='https://storage.ko-fi.com/cdn/scripts/overlay-widget.js'></script>
    <script>
      kofiWidgetOverlay.draw('dailysignal', {
        'type': 'floating-chat',
        'floating-chat.donateButton.text': 'Support me',
        'floating-chat.donateButton.background-color': '#00b9fe',
        'floating-chat.donateButton.text-color': '#fff'
      });
    </script>

email:
  enabled: false
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  use_tls: true
  from_addr: "you@example.com"
  to_addr: "you@example.com"
  username: "you@example.com"
  app_password: "APP_PASSWORD"

sources:
  nasa_apod: true
  usgs_quakes: true
  noaa_space: true
  on_this_day: true
resources:
  - title: "Aurora Forecast Map"
    url: "https://www.swpc.noaa.gov/products/aurora-30-minute-forecast"
    note: "Official NOAA nowcast"
  - title: "Emergency Quake Kit"
    url: "https://www.amazon.com/dp/B0B5H7QK1F?tag=AFFID"
    note: "Replace AFFID with your Amazon tag"
  - title: "Beginner’s Stargazing Book"
    url: "https://www.amazon.com/dp/1615194799?tag=AFFID"
    note: "Swap AFFID for your tag"
  - title: "USGS Latest Earthquakes"
    url: "https://earthquake.usgs.gov/earthquakes/map/"
    note: "Live map (official)"
