name: Build & Deploy — Daily

on:
  schedule:
    - cron: "10 14 * * *"   # 07:10 America/Vancouver
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python app.py
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

  ping:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install PyYAML
      - name: Read base_url from config.yaml
        shell: bash
        run: |
          echo "SITE=$(python - << 'PY'
          import yaml
          cfg = yaml.safe_load(open('config.yaml','r',encoding='utf-8'))
          print(cfg['site']['base_url'].rstrip('/'))
          PY
          )" >> $GITHUB_ENV
      - name: Ping sitemaps
        shell: bash
        run: |
          echo "Pinging $SITE/sitemap.xml"
          curl -fsS "https://www.google.com/ping?sitemap=$SITE/sitemap.xml" || true
          curl -fsS "https://www.bing.com/ping?sitemap=$SITE/sitemap.xml" || true
